<?php require __DIR__ . '/../partials/header.php'; ?>
<section class="section quotation-admin"><div class="container" data-reveal>
  <div class="admin-page-head"><div><p class="eyebrow">Quotation Builder</p><h1>Proposal Templates</h1><p class="muted-line">Manage proposal copy, inclusions, exclusions, payment schedule, and branding.</p></div><a class="btn-link" href="/admin/quotations">All Quotations</a></div>
  <nav class="quotation-subnav"><a href="/admin/quotations">All Quotations</a><a href="/admin/quotations/create">Create Quotation</a><a href="/admin/proposal-templates">Proposal Templates</a><a href="/admin/quotation-rate-card">Rate Card</a><a href="/admin/quotation-packages">Package Master</a><a href="/admin/quotation-settings">Settings</a></nav>
  <form id="templateForm" class="admin-card quote-master-form">
    <input type="hidden" name="id"><input type="hidden" name="payment_schedule_json" id="templateScheduleJson"><div class="budget-grid"><input name="name" placeholder="Template name *" required><input name="type" placeholder="Template type"></div>
    <div class="budget-grid"><input name="cover_title" placeholder="Cover title"><input name="accent_color" placeholder="Accent colour" value="#0d2438"></div>
    <textarea name="welcome_note" rows="3" placeholder="Welcome note"></textarea><textarea name="inclusions" rows="4" placeholder="Inclusions"></textarea><textarea name="exclusions" rows="4" placeholder="Exclusions"></textarea><textarea name="terms" rows="4" placeholder="Terms"></textarea><textarea name="warranty_text" rows="3" placeholder="Warranty text"></textarea>
    <div class="budget-grid"><input name="logo_url" placeholder="Logo URL"><input name="footer_note" placeholder="Footer note"></div>
    <textarea name="payment_schedule_json_text" rows="3" placeholder='Payment schedule JSON e.g. [{"label":"Booking amount","percentage":10}]'></textarea>
    <label class="switch-row"><input type="checkbox" name="is_active" value="1" checked> Active</label><div class="admin-links"><button class="btn-primary" type="submit">Save Template</button><button class="btn-muted" type="button" id="templateReset">Reset</button></div><p id="templateMsg" class="form-message"></p>
  </form>
  <div class="table-shell"><table><thead><tr><th>Name</th><th>Type</th><th>Cover</th><th>Accent</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach ($templates as $template): ?><tr data-row='<?= htmlspecialchars(json_encode($template), ENT_QUOTES, 'UTF-8') ?>'><td><?= htmlspecialchars((string)$template['name'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars((string)$template['type'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars((string)$template['cover_title'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars((string)$template['accent_color'], ENT_QUOTES, 'UTF-8') ?></td><td><?= !empty($template['is_active']) ? 'Active' : 'Inactive' ?></td><td><button class="btn-link edit-master" type="button">Edit</button></td></tr><?php endforeach; ?></tbody></table></div>
</div></section>
<script>
(() => { const form=document.getElementById('templateForm'), msg=document.getElementById('templateMsg'); document.querySelectorAll('.edit-master').forEach(btn=>btn.onclick=()=>{const row=JSON.parse(btn.closest('tr').dataset.row); Object.entries(row).forEach(([k,v])=>{const i=form.elements[k]; if(!i)return; if(i.type==='checkbox')i.checked=Number(v)===1; else if(k==='payment_schedule_json') form.elements.payment_schedule_json_text.value=v||''; else i.value=v??'';}); if(row.payment_schedule)form.elements.payment_schedule_json_text.value=JSON.stringify(row.payment_schedule); scrollTo({top:0,behavior:'smooth'});}); document.getElementById('templateReset').onclick=()=>form.reset(); form.onsubmit=async e=>{e.preventDefault(); let schedule=[]; try{schedule=JSON.parse(form.elements.payment_schedule_json_text.value||'[]')}catch(err){msg.className='form-message error'; msg.textContent='Payment schedule JSON is invalid.'; return;} document.getElementById('templateScheduleJson').value=JSON.stringify(schedule); const fd=new FormData(form); const id=fd.get('id'); if(id)fd.set('_method','PUT'); const r=await fetch(id?`/api/proposal-templates/${id}`:'/api/proposal-templates',{method:'POST',body:fd}); const d=await r.json(); msg.className=`form-message ${r.ok?'ok':'error'}`; msg.textContent=r.ok?'Template saved.':(d.error||'Save failed'); if(r.ok)setTimeout(()=>location.reload(),400);}; })();
</script>
<?php require __DIR__ . '/../partials/footer.php'; ?>
