<?php require __DIR__ . '/../partials/header.php'; ?>
<?php
$money = static fn(mixed $value): string => '₹' . number_format((float)$value, 0);
$designerLogo = trim((string)($quote['designer_profile_pic'] ?? '')) ?: '/logo.png';
$designerName = trim((string)($quote['designer_name'] ?? 'Interior Designer')) ?: 'Interior Designer';
$poweredBy = '<footer class="proposal-powered">Powered by homeinteriors360.com</footer>';
?>
<main class="proposal-print">
  <button class="btn-primary print-button" type="button" onclick="window.print()">Save as PDF</button>
  <section class="print-page cover"><img src="<?= htmlspecialchars($designerLogo, ENT_QUOTES, 'UTF-8') ?>" alt="<?= htmlspecialchars($designerName, ENT_QUOTES, 'UTF-8') ?>"><p class="proposal-designer-name"><?= htmlspecialchars($designerName, ENT_QUOTES, 'UTF-8') ?></p><h1><?= htmlspecialchars((string)($quote['cover_title'] ?: 'Interior Design Proposal'), ENT_QUOTES, 'UTF-8') ?></h1><p><?= htmlspecialchars((string)$quote['client_name'], ENT_QUOTES, 'UTF-8') ?> · <?= htmlspecialchars((string)$quote['quote_number'], ENT_QUOTES, 'UTF-8') ?></p><strong><?= $money($quote['final_amount']) ?></strong><?= $poweredBy ?></section>
  <section class="print-page"><h2>Project summary</h2><p><?= htmlspecialchars((string)$quote['city'], ENT_QUOTES, 'UTF-8') ?> · <?= htmlspecialchars((string)$quote['bhk'], ENT_QUOTES, 'UTF-8') ?> · <?= htmlspecialchars((string)$quote['scope_type'], ENT_QUOTES, 'UTF-8') ?> · <?= htmlspecialchars((string)($quote['package_name'] ?? ''), ENT_QUOTES, 'UTF-8') ?></p><p><?= nl2br(htmlspecialchars((string)($quote['welcome_note'] ?: $quote['client_notes']), ENT_QUOTES, 'UTF-8')) ?></p><h2>Detailed quotation</h2><table><thead><tr><th>Room</th><th>Item</th><th>Qty</th><th>Unit</th><th>Rate</th><th>Amount</th></tr></thead><tbody><?php foreach ($quote['items'] as $item): if (empty($item['include_in_proposal'])) continue; ?><tr><td><?= htmlspecialchars((string)$item['room_name'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars((string)$item['item_name'], ENT_QUOTES, 'UTF-8') ?></td><td><?= number_format((float)$item['quantity'], 2) ?></td><td><?= htmlspecialchars((string)$item['unit_type'], ENT_QUOTES, 'UTF-8') ?></td><td><?= $money($item['rate']) ?></td><td><?= $money($item['amount']) ?></td></tr><?php endforeach; ?></tbody></table><?= $poweredBy ?></section>
  <section class="print-page"><h2>Quote summary</h2><dl><div><dt>Subtotal</dt><dd><?= $money($quote['subtotal']) ?></dd></div><div><dt>Design fee</dt><dd><?= $money($quote['design_fee']) ?></dd></div><div><dt>Project management fee</dt><dd><?= $money($quote['project_management_fee']) ?></dd></div><div><dt>GST</dt><dd><?= $money($quote['gst_amount']) ?></dd></div><div><dt>Discount</dt><dd><?= $money($quote['discount_amount']) ?></dd></div><div><dt>Final quote</dt><dd><?= $money($quote['final_amount']) ?></dd></div></dl><h2>Payment schedule</h2><?php foreach ($quote['payment_schedule'] as $row): ?><p><?= htmlspecialchars((string)$row['label'], ENT_QUOTES, 'UTF-8') ?>: <?= number_format((float)($row['percentage'] ?? 0), 1) ?>% · <?= $money($row['amount'] ?? 0) ?></p><?php endforeach; ?><?= $poweredBy ?></section>
  <section class="print-page"><h2>Package, inclusions and terms</h2><p><?= htmlspecialchars((string)($quote['package_description'] ?? ''), ENT_QUOTES, 'UTF-8') ?></p><h3>Inclusions</h3><p><?= nl2br(htmlspecialchars((string)($quote['inclusions'] ?? ''), ENT_QUOTES, 'UTF-8')) ?></p><h3>Exclusions</h3><p><?= nl2br(htmlspecialchars((string)($quote['exclusions'] ?? ''), ENT_QUOTES, 'UTF-8')) ?></p><h3>Terms</h3><p><?= nl2br(htmlspecialchars((string)($quote['terms'] ?? ''), ENT_QUOTES, 'UTF-8')) ?></p><?= $poweredBy ?></section>
</main>
<?php if (!empty($autoPrint)): ?><script>setTimeout(() => window.print(), 500);</script><?php endif; ?>
<?php require __DIR__ . '/../partials/footer.php'; ?>
