-- HomeInteriors360: Professional Profiles + Portfolio Architecture

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS lead_purchase_items;
DROP TABLE IF EXISTS lead_purchases;
DROP TABLE IF EXISTS lead_coupons;
DROP TABLE IF EXISTS lead_buyers;
DROP TABLE IF EXISTS property_enquiries;
DROP TABLE IF EXISTS real_estate_floor_plans;
DROP TABLE IF EXISTS real_estate_media;
DROP TABLE IF EXISTS real_estate_units;
DROP TABLE IF EXISTS real_estate_projects;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS leads;
DROP TABLE IF EXISTS pros;
DROP TABLE IF EXISTS site_content;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  email VARCHAR(255) DEFAULT NULL,
  role ENUM('admin','super_admin','designer') NOT NULL DEFAULT 'admin',
  pro_id INT DEFAULT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_users_pro (pro_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE pros (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  profile_pic VARCHAR(500) DEFAULT NULL,
  cover_photo VARCHAR(500) DEFAULT NULL,
  role ENUM('Architect','Designer','Contractor') NOT NULL,
  profile_description TEXT,
  specialization VARCHAR(255) DEFAULT NULL,
  primary_work_type VARCHAR(120) DEFAULT NULL,
  primary_work_area VARCHAR(120) DEFAULT NULL,
  verification_status BOOLEAN NOT NULL DEFAULT FALSE,
  is_premium BOOLEAN NOT NULL DEFAULT FALSE,
  rating DECIMAL(3,2) NOT NULL DEFAULT 0,
  years_experience INT NOT NULL DEFAULT 0,
  projects_delivered INT NOT NULL DEFAULT 0,
  starting_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  min_project_value DECIMAL(12,2) DEFAULT NULL,
  max_project_value DECIMAL(12,2) DEFAULT NULL,
  consultation_fee DECIMAL(12,2) DEFAULT NULL,
  city VARCHAR(120) DEFAULT NULL,
  office_address VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(30) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  website_url VARCHAR(500) DEFAULT NULL,
  founded_year YEAR DEFAULT NULL,
  team_size INT DEFAULT NULL,
  office_hours VARCHAR(120) DEFAULT NULL,
  client_count INT DEFAULT NULL,
  service_summary TEXT,
  service_areas JSON DEFAULT NULL,
  materials_json JSON DEFAULT NULL,
  design_styles_json JSON DEFAULT NULL,
  languages_json JSON DEFAULT NULL,
  certifications_json JSON DEFAULT NULL,
  process_steps_json JSON DEFAULT NULL,
  awards_json JSON DEFAULT NULL,
  faq_json JSON DEFAULT NULL,
  response_time_hours INT DEFAULT NULL,
  bio TEXT,
  why_work_with_me TEXT,
  offerings_json JSON DEFAULT NULL,
  google_business_url VARCHAR(500) DEFAULT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_pro_role (role),
  INDEX idx_pro_city (city),
  INDEX idx_pro_primary_work_type (primary_work_type),
  INDEX idx_pro_primary_work_area (primary_work_area),
  INDEX idx_pro_verified (verification_status),
  INDEX idx_pro_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pro_id INT NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  project_name VARCHAR(255) NOT NULL,
  project_description TEXT,
  total_cost DECIMAL(12,2) NOT NULL DEFAULT 0,
  bhk_type ENUM('1BHK','2BHK','3BHK','4BHK','Villa','Commercial') NOT NULL DEFAULT '2BHK',
  year_completed YEAR DEFAULT NULL,
  timeline_months INT NOT NULL DEFAULT 0,
  project_duration_label VARCHAR(120) DEFAULT NULL,
  location VARCHAR(255) DEFAULT NULL,
  work_type VARCHAR(120) DEFAULT NULL,
  area_of_work VARCHAR(120) DEFAULT NULL,
  materials_json JSON DEFAULT NULL,
  media_json JSON DEFAULT NULL,
  video_url VARCHAR(500) DEFAULT NULL,
  design_style VARCHAR(120) DEFAULT NULL,
  team_size INT DEFAULT NULL,
  warranty_years INT DEFAULT NULL,
  testimonial_client_name VARCHAR(255) DEFAULT NULL,
  testimonial_text TEXT,
  testimonial_rating TINYINT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_projects_pro FOREIGN KEY (pro_id) REFERENCES pros(id) ON DELETE CASCADE,
  INDEX idx_projects_pro (pro_id),
  INDEX idx_projects_location (location),
  INDEX idx_projects_work_type (work_type),
  INDEX idx_projects_area_of_work (area_of_work)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pro_id INT NOT NULL,
  client_name VARCHAR(255) NOT NULL,
  rating TINYINT NOT NULL DEFAULT 5,
  review_text TEXT NOT NULL,
  verified_purchase BOOLEAN NOT NULL DEFAULT FALSE,
  work_type VARCHAR(120) DEFAULT NULL,
  area_of_work VARCHAR(120) DEFAULT NULL,
  materials_highlight VARCHAR(255) DEFAULT NULL,
  photos_json JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_reviews_pro FOREIGN KEY (pro_id) REFERENCES pros(id) ON DELETE CASCADE,
  INDEX idx_reviews_pro (pro_id),
  INDEX idx_reviews_verified (verified_purchase)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE site_content (
  id INT AUTO_INCREMENT PRIMARY KEY,
  key_name VARCHAR(190) NOT NULL UNIQUE,
  content_value LONGTEXT NOT NULL,
  content_type ENUM('text','json','html') NOT NULL DEFAULT 'text',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_site_content_key (key_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE leads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  city VARCHAR(120) NOT NULL,
  society_area VARCHAR(255) DEFAULT NULL,
  budget VARCHAR(120) DEFAULT NULL,
  requirement TEXT NOT NULL,
  pro_id INT DEFAULT NULL,
  plan_type VARCHAR(80) DEFAULT NULL,
  source ENUM('homepage','profile','calculator','pricing') NOT NULL DEFAULT 'homepage',
  status ENUM('new','contacted','converted') NOT NULL DEFAULT 'new',
  floor_plan ENUM('1BHK','2BHK','3BHK','4BHK') DEFAULT NULL,
  package_tier ENUM('Essential','Premium','Luxury') DEFAULT NULL,
  rooms_json JSON DEFAULT NULL,
  estimate DECIMAL(12,2) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_leads_pro FOREIGN KEY (pro_id) REFERENCES pros(id) ON DELETE SET NULL,
  INDEX idx_leads_status (status),
  INDEX idx_leads_city (city),
  INDEX idx_leads_source (source)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE societies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  city VARCHAR(120) NOT NULL DEFAULT '',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_societies_city_name (city, name),
  INDEX idx_societies_name (name),
  INDEX idx_societies_city (city),
  INDEX idx_societies_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE lead_buyers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(30) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_lead_buyers_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE lead_coupons (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(80) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  discount_type ENUM('percentage','flat') NOT NULL DEFAULT 'percentage',
  discount_value DECIMAL(12,2) NOT NULL DEFAULT 0,
  min_leads INT DEFAULT NULL,
  max_leads INT DEFAULT NULL,
  min_order_amount DECIMAL(12,2) DEFAULT NULL,
  max_discount_amount DECIMAL(12,2) DEFAULT NULL,
  valid_from DATE DEFAULT NULL,
  valid_to DATE DEFAULT NULL,
  usage_limit INT DEFAULT NULL,
  used_count INT NOT NULL DEFAULT 0,
  show_on_frontend BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_lead_coupons_frontend (show_on_frontend, is_active),
  INDEX idx_lead_coupons_dates (valid_from, valid_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE lead_purchases (
  id INT AUTO_INCREMENT PRIMARY KEY,
  buyer_id INT NOT NULL,
  razorpay_order_id VARCHAR(120) NOT NULL,
  razorpay_payment_id VARCHAR(120) DEFAULT NULL,
  razorpay_signature VARCHAR(255) DEFAULT NULL,
  coupon_code VARCHAR(80) DEFAULT NULL,
  discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  amount_total DECIMAL(12,2) NOT NULL DEFAULT 0,
  currency VARCHAR(12) NOT NULL DEFAULT 'INR',
  payment_status ENUM('pending','paid','failed') NOT NULL DEFAULT 'pending',
  cart_json JSON DEFAULT NULL,
  paid_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_lead_purchases_buyer FOREIGN KEY (buyer_id) REFERENCES lead_buyers(id) ON DELETE CASCADE,
  UNIQUE KEY uniq_lead_purchase_order (razorpay_order_id),
  INDEX idx_lead_purchases_buyer (buyer_id),
  INDEX idx_lead_purchases_status (payment_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE lead_purchase_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  purchase_id INT NOT NULL,
  buyer_id INT NOT NULL,
  filter_name VARCHAR(255) NOT NULL,
  filter_json JSON NOT NULL,
  date_filter VARCHAR(40) DEFAULT NULL,
  leads_count INT NOT NULL DEFAULT 0,
  amount_total DECIMAL(12,2) NOT NULL DEFAULT 0,
  pricing_json JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_lead_purchase_items_purchase FOREIGN KEY (purchase_id) REFERENCES lead_purchases(id) ON DELETE CASCADE,
  CONSTRAINT fk_lead_purchase_items_buyer FOREIGN KEY (buyer_id) REFERENCES lead_buyers(id) ON DELETE CASCADE,
  INDEX idx_lead_purchase_items_buyer (buyer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE real_estate_projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(255) NOT NULL UNIQUE,
  project_name VARCHAR(255) NOT NULL,
  listing_for ENUM('buy','rent','both') NOT NULL DEFAULT 'buy',
  property_type VARCHAR(120) NOT NULL,
  project_status VARCHAR(80) DEFAULT NULL,
  builder_name VARCHAR(255) DEFAULT NULL,
  rera_number VARCHAR(120) DEFAULT NULL,
  possession_date DATE DEFAULT NULL,
  address VARCHAR(500) DEFAULT NULL,
  locality VARCHAR(180) DEFAULT NULL,
  city VARCHAR(120) NOT NULL,
  state VARCHAR(120) DEFAULT NULL,
  pincode VARCHAR(12) DEFAULT NULL,
  latitude DECIMAL(10,7) DEFAULT NULL,
  longitude DECIMAL(10,7) DEFAULT NULL,
  short_description TEXT,
  description LONGTEXT,
  price_min DECIMAL(14,2) NOT NULL DEFAULT 0,
  price_max DECIMAL(14,2) NOT NULL DEFAULT 0,
  rent_min DECIMAL(14,2) NOT NULL DEFAULT 0,
  rent_max DECIMAL(14,2) NOT NULL DEFAULT 0,
  price_per_sqft DECIMAL(12,2) DEFAULT NULL,
  area_min INT DEFAULT NULL,
  area_max INT DEFAULT NULL,
  total_units INT DEFAULT NULL,
  total_towers INT DEFAULT NULL,
  total_area_acres DECIMAL(8,2) DEFAULT NULL,
  video_url VARCHAR(500) DEFAULT NULL,
  brochure_url VARCHAR(500) DEFAULT NULL,
  amenities_json JSON DEFAULT NULL,
  highlights_json JSON DEFAULT NULL,
  nearby_json JSON DEFAULT NULL,
  meta_title VARCHAR(255) DEFAULT NULL,
  meta_description VARCHAR(500) DEFAULT NULL,
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_re_project_listing (listing_for, is_active),
  INDEX idx_re_project_city (city, locality),
  INDEX idx_re_project_type (property_type),
  INDEX idx_re_project_price (price_min, price_max),
  INDEX idx_re_project_rent (rent_min, rent_max)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE real_estate_units (
  id INT AUTO_INCREMENT PRIMARY KEY,
  project_id INT NOT NULL,
  unit_name VARCHAR(180) NOT NULL,
  bhk_type VARCHAR(80) DEFAULT NULL,
  unit_type VARCHAR(120) DEFAULT NULL,
  carpet_area INT DEFAULT NULL,
  builtup_area INT DEFAULT NULL,
  balconies INT DEFAULT NULL,
  bathrooms INT DEFAULT NULL,
  furnishing VARCHAR(80) DEFAULT NULL,
  sale_price DECIMAL(14,2) NOT NULL DEFAULT 0,
  monthly_rent DECIMAL(14,2) NOT NULL DEFAULT 0,
  maintenance_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  available_units INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_re_units_project FOREIGN KEY (project_id) REFERENCES real_estate_projects(id) ON DELETE CASCADE,
  INDEX idx_re_units_project (project_id, is_active),
  INDEX idx_re_units_bhk (bhk_type),
  INDEX idx_re_units_sale_price (sale_price),
  INDEX idx_re_units_rent (monthly_rent)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE real_estate_media (
  id INT AUTO_INCREMENT PRIMARY KEY,
  project_id INT NOT NULL,
  media_type ENUM('image','video') NOT NULL DEFAULT 'image',
  media_url VARCHAR(500) NOT NULL,
  title VARCHAR(255) DEFAULT NULL,
  category VARCHAR(80) DEFAULT NULL,
  is_cover BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_re_media_project FOREIGN KEY (project_id) REFERENCES real_estate_projects(id) ON DELETE CASCADE,
  INDEX idx_re_media_project (project_id, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE real_estate_floor_plans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  project_id INT NOT NULL,
  unit_id INT DEFAULT NULL,
  title VARCHAR(255) NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  area_label VARCHAR(120) DEFAULT NULL,
  price_label VARCHAR(120) DEFAULT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_re_floor_project FOREIGN KEY (project_id) REFERENCES real_estate_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_re_floor_unit FOREIGN KEY (unit_id) REFERENCES real_estate_units(id) ON DELETE SET NULL,
  INDEX idx_re_floor_project (project_id, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE property_enquiries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  project_id INT NOT NULL,
  unit_id INT DEFAULT NULL,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  email VARCHAR(255) DEFAULT NULL,
  requirement ENUM('buy','rent') NOT NULL DEFAULT 'buy',
  message TEXT,
  consent BOOLEAN NOT NULL DEFAULT FALSE,
  source VARCHAR(80) NOT NULL DEFAULT 'project_detail',
  status ENUM('new','contacted','qualified','closed') NOT NULL DEFAULT 'new',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_property_enquiry_project FOREIGN KEY (project_id) REFERENCES real_estate_projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_property_enquiry_unit FOREIGN KEY (unit_id) REFERENCES real_estate_units(id) ON DELETE SET NULL,
  INDEX idx_property_enquiry_project (project_id),
  INDEX idx_property_enquiry_status (status),
  INDEX idx_property_enquiry_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO users (username, password_hash, email, role, is_active)
VALUES
  ('admin', '$2y$12$Pvz8JNRFpPwoAdeEEn2/gO7ujmJNBng4yu.WFM2e3JGsw1XI8QQDa', 'jitender@homeinteriors360.com', 'super_admin', 1)
ON DUPLICATE KEY UPDATE email = VALUES(email), role = VALUES(role), is_active = VALUES(is_active);

INSERT INTO pros (
  full_name, slug, profile_pic, cover_photo, role, profile_description, specialization,
  primary_work_type, primary_work_area, verification_status, is_premium, rating, years_experience, projects_delivered,
  starting_price, min_project_value, max_project_value, consultation_fee, city, service_areas,
  materials_json, design_styles_json, languages_json, certifications_json, response_time_hours,
  bio, why_work_with_me, offerings_json, is_active
)
VALUES
(
  'Ananya Sharma Interiors',
  'ananya-sharma-interiors',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'https://images.unsplash.com/photo-1616137466211-f939a420be84?auto=format&fit=crop&w=1600&q=80',
  'Designer',
  'Premium turnkey interiors with deep focus on Indian family lifestyles and practical luxury.',
  'Residential Turnkey Designer',
  'Full Home',
  'Apartments',
  1,
  1,
  4.9,
  12,
  64,
  550000,
  450000,
  3500000,
  2500,
  'Gurgaon',
  JSON_ARRAY('Delhi', 'Gurgaon', 'Noida'),
  JSON_ARRAY('BWP Plywood', 'Hafele Hardware', 'Acrylic Laminate', 'Quartz Countertop'),
  JSON_ARRAY('Modern Indian', 'Contemporary', 'Minimal Luxe'),
  JSON_ARRAY('Hindi', 'English'),
  JSON_ARRAY('ISO Process Partner', 'Hafele Certified Installer Network'),
  3,
  'We create homes that balance aesthetic clarity, storage logic, and long-term durability.',
  'Single-point accountability, transparent costing, and weekly progress reviews.',
  JSON_ARRAY('Modular Kitchen', 'Wardrobes', 'TV Unit', 'False Ceiling', 'Full Home Interiors'),
  1
),
(
  'Raghav Menon Architects',
  'raghav-menon-architects',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'Architect',
  'Architecture-led interiors for villas and large format residences.',
  'Architecture + Interior Integration',
  'Renovation',
  'Villa',
  1,
  1,
  4.7,
  15,
  41,
  850000,
  700000,
  5500000,
  4000,
  'Delhi',
  JSON_ARRAY('Delhi', 'Noida', 'Gurgaon'),
  JSON_ARRAY('Natural Veneer', 'PU Finish', 'Engineered Wood', 'Imported Marble'),
  JSON_ARRAY('Contemporary', 'Neo-classical', 'Warm Modern'),
  JSON_ARRAY('Hindi', 'English', 'Malayalam'),
  JSON_ARRAY('COA Registered Practice', 'IGBC Trained Team'),
  5,
  'We design architecture and interiors as one system for stronger flow and better quality.',
  'Precision planning, disciplined detailing, and high-end finish control.',
  JSON_ARRAY('Space Planning', 'Renovation', 'Civil Layout', 'Lighting Design', 'Turnkey Build Coordination'),
  1
),
(
  'Vikas Bedi Contracting',
  'vikas-bedi-contracting',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=1600&q=80',
  'Contractor',
  'Execution-first contractor with strong civil, MEP, and modular coordination.',
  'Turnkey Contractor',
  'Execution',
  'Commercial',
  1,
  0,
  4.6,
  14,
  89,
  400000,
  300000,
  4000000,
  1800,
  'Noida',
  JSON_ARRAY('Noida', 'Delhi', 'Gurgaon'),
  JSON_ARRAY('Greenply', 'CenturyPly', 'Asian Paints', 'Kajaria'),
  JSON_ARRAY('Practical Modern', 'Industrial', 'Budget Premium'),
  JSON_ARRAY('Hindi', 'English', 'Punjabi'),
  JSON_ARRAY('Site Safety Certified Supervisors'),
  6,
  'We execute interiors with strict supervision, quality checkpoints, and practical scheduling.',
  'Daily updates, milestone billing, and on-site accountability till handover.',
  JSON_ARRAY('Civil Work', 'Electrical', 'Plumbing', 'Modular Installation', 'Paint & Polish'),
  1
),
(
  'Neev Interiors',
  'neev-interiors-gurgaon',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'Designer',
  'Luxury home interiors with practical space planning for Gurgaon apartments and villas.',
  'Luxury Residential Interiors',
  'Full Home',
  'Apartments',
  1,
  1,
  4.8,
  11,
  58,
  600000,
  500000,
  4200000,
  3000,
  'Gurgaon',
  JSON_ARRAY('Golf Course Road', 'DLF Phase 1', 'Sohna Road', 'Sector 57'),
  JSON_ARRAY('BWP Plywood', 'Acrylic Finish', 'Hafele Hardware', 'Quartz', 'PU Paint'),
  JSON_ARRAY('Modern', 'Minimal Luxe', 'Warm Contemporary'),
  JSON_ARRAY('Hindi', 'English'),
  JSON_ARRAY('Premium Modular Partner', 'Space Planning Certified'),
  3,
  'We build premium homes around storage, light, and daily use patterns.',
  'Design clarity, site discipline, and a polished handover experience.',
  JSON_ARRAY('Full Home Interiors', 'Wardrobes', 'Kitchen', 'Lighting', 'False Ceiling'),
  1
),
(
  'Tribuz Interiors',
  'tribuz-interiors-gurgaon',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'Designer',
  'Thoughtfully curated spaces that balance modern sophistication with functional planning.',
  'Luxury Home & Office Design',
  'Full Home',
  'Apartments',
  1,
  1,
  4.7,
  9,
  44,
  550000,
  450000,
  3800000,
  2500,
  'Gurgaon',
  JSON_ARRAY('Golf Course Extension', 'Sector 66', 'DLF Phase 5', 'Sohna Road'),
  JSON_ARRAY('Marine Plywood', 'PU Finish', 'Hafele', 'Natural Veneer'),
  JSON_ARRAY('Contemporary', 'Luxury Modern', 'Minimal'),
  JSON_ARRAY('Hindi', 'English'),
  JSON_ARRAY('Turnkey Delivery Process', 'Interior Workflow Planning'),
  4,
  'We keep the process transparent and the design language clean.',
  'Smart layouts, premium detailing, and consistent communication.',
  JSON_ARRAY('Residential Interiors', 'Office Interiors', 'Wardrobes', 'Modular Kitchens'),
  1
),
(
  'Silqe Design Studio',
  'silqe-design-studio-gurgaon',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'Architect',
  'High-end turnkey homes across Gurgaon’s premium neighborhoods.',
  'Turnkey Luxury Interiors',
  'Renovation',
  'Villa',
  1,
  1,
  4.9,
  13,
  67,
  700000,
  650000,
  5200000,
  4000,
  'Gurgaon',
  JSON_ARRAY('Golf Course Road', 'DLF Phase 4', 'DLF Phase 5', 'Sushant Lok'),
  JSON_ARRAY('Imported Veneer', 'Quartzite', 'Microtopping', 'Solid Surface'),
  JSON_ARRAY('Modern Luxe', 'Arched Contemporary', 'Soft Minimal'),
  JSON_ARRAY('Hindi', 'English'),
  JSON_ARRAY('Architecture + Interiors Integration', 'Turnkey Project Management'),
  2,
  'We design high-touch luxury homes with disciplined detailing.',
  'Architectural planning, material curation, and sharp execution control.',
  JSON_ARRAY('Villas', 'Penthouses', 'Renovation', 'Custom Furniture', 'Lighting'),
  1
),
(
  'ClassyGaze Interiors',
  'classygaze-interiors-gurgaon',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'Designer',
  'Residential and workplace interiors focused on comfort, usability, and a premium finish.',
  'Home & Workplace Design',
  'Full Home',
  'Commercial',
  1,
  0,
  4.6,
  8,
  33,
  420000,
  300000,
  2800000,
  1800,
  'Gurgaon',
  JSON_ARRAY('Sector 48', 'Udyog Vihar', 'Golf Course Extension', 'Sohna Road'),
  JSON_ARRAY('BWP Plywood', 'Acrylic Shutters', 'PU Paint', 'Quartz'),
  JSON_ARRAY('Modern', 'Contemporary', 'Warm Neutral'),
  JSON_ARRAY('Hindi', 'English'),
  JSON_ARRAY('Space Optimization Focus', 'Material Coordination'),
  5,
  'We create comfortable spaces that are practical for daily use and long-term maintenance.',
  'Responsive design development, faster handovers, and cleaner finish checks.',
  JSON_ARRAY('Residential Design', 'Office Interiors', 'Kitchen', 'Wardrobe'),
  1
),
(
  'SS Interior Solution',
  'ss-interior-solution-gurgaon',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'Contractor',
  'Turnkey residential execution with modular and civil coordination in Gurgaon.',
  'Modular + Turnkey Execution',
  'Kitchen',
  'Apartments',
  1,
  0,
  4.5,
  16,
  96,
  280000,
  220000,
  2600000,
  1500,
  'Gurgaon',
  JSON_ARRAY('Sector 46', 'Sector 56', 'Sohna Road', 'Golf Course Road'),
  JSON_ARRAY('Greenply', 'CenturyPly', 'Hettich', 'Asian Paints'),
  JSON_ARRAY('Practical Modern', 'Budget Premium', 'Functional'),
  JSON_ARRAY('Hindi', 'English'),
  JSON_ARRAY('Execution Team', 'On-Site Supervision'),
  6,
  'We manage execution with discipline and reliable milestone control.',
  'Site coordination, quality checks, and practical material choices.',
  JSON_ARRAY('Civil', 'Electrical', 'Plumbing', 'Modular Kitchen', 'Wardrobes'),
  1
),
(
  'Pahal Design Studio',
  'pahal-design-studio-gurgaon',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'Designer',
  'A design-first studio making compact Gurgaon homes feel larger and more composed.',
  'Space Efficient Interiors',
  'Wardrobe',
  'Apartments',
  1,
  0,
  4.4,
  7,
  29,
  380000,
  250000,
  2200000,
  1200,
  'Gurgaon',
  JSON_ARRAY('Sector 67', 'Sector 56', 'DLF Phase 3', 'Sushant Lok'),
  JSON_ARRAY('Laminate', 'Marine Plywood', 'PU Paint', 'Soft Close Hardware'),
  JSON_ARRAY('Minimal', 'Modern', 'Scandinavian'),
  JSON_ARRAY('Hindi', 'English'),
  JSON_ARRAY('Compact Home Specialist', 'Custom Storage Planning'),
  5,
  'We focus on compact homes that still feel calm, bright, and premium.',
  'Better storage planning and layouts that are easy to live with.',
  JSON_ARRAY('Wardrobes', 'Compact Kitchens', 'TV Units', 'Study Units'),
  1
),
(
  'Archone Studio',
  'archone-studio-gurgaon',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'Architect',
  'Custom luxury interiors with architecture-led planning for modern Gurgaon homes.',
  'Custom Luxury Interiors',
  'Renovation',
  'Villa',
  1,
  1,
  4.8,
  14,
  52,
  680000,
  550000,
  4800000,
  3500,
  'Gurgaon',
  JSON_ARRAY('Golf Course Road', 'DLF Phase 2', 'Sector 57', 'Sushant Lok'),
  JSON_ARRAY('Veneer', 'Quartz', 'Hafele', 'PU Finish'),
  JSON_ARRAY('Contemporary', 'Luxury', 'Warm Minimal'),
  JSON_ARRAY('Hindi', 'English'),
  JSON_ARRAY('Architecture + Interior Consultancy', 'Luxury Detailing'),
  4,
  'We combine architectural clarity with warm luxury interiors.',
  'Strong concept direction, careful detailing, and premium finish control.',
  JSON_ARRAY('Villas', 'Luxury Homes', 'Renovation', 'Kitchen', 'Wardrobes'),
  1
),
(
  'Melange by Sangeeta Kapoor',
  'melange-by-sangeeta-kapoor-gurgaon',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
  'Designer',
  'Luxury interiors for contemporary Gurgaon residences with bespoke styling and polished execution.',
  'Luxury Interior Design Studio',
  'Full Home',
  'Apartments',
  1,
  1,
  4.9,
  12,
  61,
  750000,
  650000,
  5500000,
  5000,
  'Gurgaon',
  JSON_ARRAY('DLF City Phase 1', 'Golf Course Extension', 'Sohna Road', 'Sector 42'),
  JSON_ARRAY('Bespoke Veneer', 'Natural Stone', 'Hafele', 'Luxury Fabrics'),
  JSON_ARRAY('Modern Luxury', 'Warm Contemporary', 'Artistic'),
  JSON_ARRAY('Hindi', 'English'),
  JSON_ARRAY('Bespoke Styling', 'Luxury Client Experience'),
  2,
  'We create highly personalized homes with a boutique design touch.',
  'Tailored concept boards, curated materials, and strong visual storytelling.',
  JSON_ARRAY('Luxury Homes', 'Styling', 'Full Home Interiors', 'Wardrobes', 'Kitchen'),
  1
);

INSERT INTO projects (
  pro_id, slug, project_name, project_description, total_cost, bhk_type, year_completed,
  timeline_months, project_duration_label, location, work_type, area_of_work, materials_json,
  media_json, video_url, design_style, team_size, warranty_years,
  testimonial_client_name, testimonial_text, testimonial_rating
)
VALUES
(
  1,
  'dlf-camellias-4bhk-turnkey',
  'DLF Camellias 4BHK Turnkey',
  'Complete 4BHK transformation with bespoke storage, Italian-themed kitchen finishes, and layered lighting.',
  4200000,
  '4BHK',
  2025,
  7,
  '7 months',
  'DLF Camellias, Gurgaon',
  'Full Home',
  'Apartments',
  JSON_ARRAY('BWP Plywood', 'Acrylic Shutters', 'Hafele Fittings', 'Quartz Countertop'),
  JSON_ARRAY(
    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1500&q=80',
    'https://images.pexels.com/photos/6585750/pexels-photo-6585750.jpeg?auto=compress&cs=tinysrgb&w=1500',
    'https://images.unsplash.com/photo-1615529182904-14819c35db37?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1500&q=80'
  ),
  'https://www.youtube.com/embed/ScMzIvxBSi4',
  'Modern Indian',
  18,
  10,
  'Ritika Arora',
  'Execution quality and detailing exceeded expectations. The site updates were always transparent.',
  5
),
(
  1,
  'sector56-kitchen-wardrobe-upgrade',
  'Sector 56 Kitchen + Wardrobe Upgrade',
  'Targeted renovation for kitchen workflow and bedroom storage with better ergonomics and finish quality.',
  980000,
  '3BHK',
  2024,
  3,
  '12 weeks',
  'Sector 56, Gurgaon',
  'Kitchen',
  'Apartments',
  JSON_ARRAY('Marine Plywood', 'PU Paint', 'Hettich Channels'),
  JSON_ARRAY(
    'https://images.unsplash.com/photo-1556912167-f556f1f39fdf?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1600489000022-c2086d79f9d4?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1500&q=80'
  ),
  NULL,
  'Contemporary',
  9,
  5,
  'Manish Jain',
  'Great storage planning and a very neat finish in both kitchen and wardrobes.',
  5
),
(
  2,
  'greater-kailash-villa-renovation',
  'Greater Kailash Villa Renovation',
  'Architecture-led renovation with façade refresh, interior remodelling, and premium material layering.',
  6100000,
  'Villa',
  2025,
  9,
  '9 months',
  'Greater Kailash, Delhi',
  'Renovation',
  'Villa',
  JSON_ARRAY('Natural Veneer', 'Imported Marble', 'Solid Wood Doors'),
  JSON_ARRAY(
    'https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?auto=format&fit=crop&w=1500&q=80',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s'
  ),
  NULL,
  'Neo-classical',
  24,
  12,
  'S. Narang',
  'From design approvals to execution sequencing, everything stayed very structured.',
  5
),
(
  3,
  'noida-corporate-execution-package',
  'Noida Corporate Office Execution',
  'Fast-paced commercial office fit-out with MEP coordination and robust site governance.',
  2800000,
  'Commercial',
  2024,
  4,
  '16 weeks',
  'Sector 62, Noida',
  'Execution',
  'Commercial',
  JSON_ARRAY('Gypsum Board', 'Modular Workstations', 'Commercial Grade Laminate'),
  JSON_ARRAY(
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s'
  ),
  NULL,
  'Industrial',
  15,
  3,
  'Arpit Khanna',
  'Clear daily supervision and dependable delivery against our timeline.',
  4
);

INSERT INTO reviews (pro_id, client_name, rating, review_text, verified_purchase, work_type, area_of_work, materials_highlight, photos_json)
VALUES
  (1, 'Rohit Mehra', 5, 'Excellent design clarity and very disciplined execution management.', 1, 'Full Home', 'Apartments', 'Acrylic + Quartz', JSON_ARRAY('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s')),
  (1, 'Neha Bansal', 5, 'Great balance between aesthetics and storage practicality.', 1, 'Kitchen', 'Apartments', 'Hafele + Marine Ply', JSON_ARRAY()),
  (2, 'Sanjana Arora', 4, 'Strong architecture-led planning and better site sequencing.', 0, 'Renovation', 'Villa', 'Natural Veneer', JSON_ARRAY()),
  (3, 'Akash Verma', 5, 'Very dependable contractor team and transparent milestone billing.', 1, 'Execution', 'Commercial', 'CenturyPly + Kajaria', JSON_ARRAY());

INSERT INTO site_content (key_name, content_value, content_type)
VALUES
  ('seo.home.title', 'HomeInteriors360 | Premium Interior Design in Delhi NCR', 'text'),
  ('seo.home.description', 'Find verified architects, interior designers, and contractors for your home project.', 'text'),
  ('seo.directory.title', 'Find Professionals | HomeInteriors360', 'text'),
  ('seo.directory.description', 'Browse verified architects, interior designers, and contractors with filters for city, work type, budget, experience, and rating.', 'text'),
  ('seo.pricing.title', 'Pricing for Architects & Interior Designers | HomeInteriors360', 'text'),
  ('seo.pricing.description', 'Choose lead purchase or managed account plans for architects and interior designers, with sales registration and growth support.', 'text'),
  ('seo.profile.title_suffix', 'Profile | HomeInteriors360', 'text'),
  ('seo.profile.description', 'Explore professional profiles, portfolio projects, materials used, testimonials, and request a quote.', 'text'),
  ('seo.portfolio.title_suffix', 'Portfolio | HomeInteriors360', 'text'),
  ('seo.portfolio.description', 'View project details, gallery images, costing, materials, and testimonials for each portfolio item.', 'text'),
  ('seo.calculator.title', 'Design Cost Calculator | HomeInteriors360', 'text'),
  ('seo.calculator.description', 'Estimate your interior design cost in a few steps and save your lead request with HomeInteriors360.', 'text'),

  ('nav.home', 'Home', 'text'),
  ('nav.directory', 'Find Professionals', 'text'),
  ('nav.pricing', 'Pricing', 'text'),
  ('nav.calculator', 'Cost Calculator', 'text'),
  ('nav.admin', 'Admin', 'text'),

  ('footer.tagline', 'Designed for modern homes across Delhi NCR', 'text'),
  ('footer.copy', 'HomeInteriors360. All rights reserved.', 'text'),

  ('home.hero.eyebrow', 'TURNKEY INTERIORS, BEAUTIFULLY EXECUTED', 'text'),
  ('home.hero.title', 'Design your dream home with verified experts.', 'text'),
  ('home.hero.subtitle', 'From modular kitchens to complete home interiors, compare top-rated professionals and start with confidence.', 'text'),
  ('home.hero.assets', '["https://images.unsplash.com/photo-1616137466211-f939a420be84?auto=format&fit=crop&w=1800&q=80","https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1800&q=80"]', 'json'),

  ('home.lead.title', 'Get Free Design Consultation', 'text'),
  ('home.lead.step1_label', 'Choose your city', 'text'),
  ('home.lead.step2_label', 'What do you want to design?', 'text'),
  ('home.lead.step3_label', 'Share contact details', 'text'),
  ('home.lead.step_next', 'Next', 'text'),
  ('home.lead.step_prev', 'Back', 'text'),
  ('home.lead.submit', 'Request Callback', 'text'),
  ('home.lead.success', 'Thank you. Our team will call you shortly.', 'text'),

  ('home.aggregators.title', 'Top Aggregators', 'text'),
  ('home.aggregators.subtitle', 'Compare verified professionals and choose what fits your vision.', 'text'),

  ('home.services.title', 'Services', 'text'),
  ('home.services.items', '[{"key":"kitchen","title":"Kitchen","description":"Smart layouts, premium finishes, durable modules.","icon":"🍽️","image":"https://images.unsplash.com/photo-1556912167-f556f1f39fdf?auto=format&fit=crop&w=1200&q=80"},{"key":"wardrobe","title":"Wardrobe","description":"Tailored storage for every room.","icon":"🗄️","image":"https://images.pexels.com/photos/6585750/pexels-photo-6585750.jpeg?auto=compress&cs=tinysrgb&w=1200"},{"key":"full_home","title":"Full Home","description":"End-to-end interiors with single-point accountability.","icon":"🏠","image":"https://images.unsplash.com/photo-1615529182904-14819c35db37?auto=format&fit=crop&w=1200&q=80"}]', 'json'),

  ('home.testimonials.title', 'Client Testimonials', 'text'),
  ('home.testimonials.items', '[{"name":"Priya S","text":"Excellent planning and execution. The handover quality was premium.","location":"Gurgaon","image":"https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=900"},{"name":"Vikas A","text":"Great design team and responsive project updates.","location":"Noida","image":"https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=900"},{"name":"Karan M","text":"We loved the modular kitchen and wardrobe detailing.","location":"Delhi","image":"https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=900"}]', 'json'),

  ('home.brands.title', 'Brands We Use', 'text'),
  ('home.brands.logos', '[{"name":"Hafele","logo":"https://upload.wikimedia.org/wikipedia/commons/2/2a/Haefele_Logo.png"},{"name":"Hettich","logo":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Logo_of_Hettich_%28company%29.svg/960px-Logo_of_Hettich_%28company%29.svg.png"},{"name":"Asian Paints","logo":"https://upload.wikimedia.org/wikipedia/commons/0/09/Asian_paints_logo.jpg"},{"name":"Kajaria","logo":"https://companieslogo.com/img/orig/KAJARIACER.NS_BIG-300b5e39.png?download=true&t=1720244492"}]', 'json'),

  ('home.trust.title', 'Why Trust Us', 'text'),
  ('home.trust.items', '["Verified professionals reviewed for quality and accountability","Dedicated design review and project support","Site supervision at every major milestone","Smooth handover and closure tracking"]', 'json'),
  ('home.usp.title', 'Our USP', 'text'),
  ('home.usp.items', '["Lead generation and qualification workflow","Portfolio and profile management for pros","Brand visibility across all listing pages","Sales-assisted account growth support"]', 'json'),

  ('directory.title', 'Find Professionals', 'text'),
  ('directory.subtitle', 'Filter by profession, budget, work type, and area to shortlist instantly.', 'text'),
  ('directory.filter.role', 'Profession', 'text'),
  ('directory.filter.city', 'City', 'text'),
  ('directory.filter.budget', 'Budget Range', 'text'),
  ('directory.filter.work_type', 'Type of Work', 'text'),
  ('directory.filter.work_area', 'Area of Work', 'text'),
  ('directory.empty', 'No professionals found for current filters.', 'text'),
  ('directory.cta', 'View Profile', 'text'),
  ('directory.verified', 'Verified', 'text'),
  ('directory.starting_from', 'Starting Price', 'text'),
  ('directory.experience', 'Years of Experience', 'text'),

  ('pricing.hero.eyebrow', 'CHOOSE YOUR GROWTH MODEL', 'text'),
  ('pricing.hero.title', 'A pricing page built for architects and interior designers.', 'text'),
  ('pricing.hero.subtitle', 'Pick the lead purchase mode or let our team manage your entire account end-to-end.', 'text'),
  ('pricing.plans.title', 'Two ways to grow', 'text'),
  ('pricing.plans.subtitle', 'Start with lead buying or hand over the full growth engine to our team.', 'text'),
  ('pricing.why.title', 'Why buy from us', 'text'),
  ('pricing.offerings.title', 'What we offer', 'text'),
  ('pricing.reviews.title', 'Best architect reviews', 'text'),
  ('pricing.form.title', 'Register interest', 'text'),
  ('pricing.form.subtitle', 'Our sales team will connect with you and tailor the right plan.', 'text'),
  ('pricing.form.submit', 'Connect with Sales', 'text'),
  ('pricing.form.success', 'Thanks. Our sales team will contact you shortly.', 'text'),

  ('profile.cta', 'Request Quote', 'text'),
  ('profile.lead.title', 'Get Project Proposal from this Professional', 'text'),
  ('profile.portfolio.title', 'Portfolio', 'text'),
  ('profile.reviews.title', 'Customer Reviews', 'text'),
  ('profile.expertise.title', 'Expertise & Offerings', 'text'),
  ('profile.materials.title', 'Preferred Materials', 'text'),
  ('profile.work_type', 'Type of Work', 'text'),
  ('profile.work_area', 'Area of Work', 'text'),
  ('profile.response_time', 'Average Response Time', 'text'),
  ('profile.languages', 'Languages', 'text'),
  ('profile.verified_purchase', 'Verified Purchase', 'text'),
  ('profile.timeline', 'Timeline', 'text'),
  ('profile.amount_spent', 'Total Amount Spent', 'text'),
  ('profile.area', 'Area of Service', 'text'),
  ('profile.materials_used', 'Materials Used', 'text'),
  ('profile.project_details', 'View Project Details', 'text'),

  ('portfolio.hero.title', 'Project Portfolio Details', 'text'),
  ('portfolio.video.title', 'Project Video', 'text'),
  ('portfolio.more_projects', 'More Projects by this Professional', 'text'),
  ('portfolio.design_style', 'Design Style', 'text'),
  ('portfolio.team_size', 'Team Size', 'text'),
  ('portfolio.warranty', 'Warranty', 'text'),

  ('ui.name', 'Name', 'text'),
  ('ui.phone', 'Phone', 'text'),
  ('ui.city', 'City', 'text'),
  ('ui.requirement', 'Requirement', 'text'),
  ('ui.society_area', 'Society / Area', 'text'),
  ('ui.budget', 'Budget', 'text')
ON DUPLICATE KEY UPDATE content_value = VALUES(content_value), content_type = VALUES(content_type);

INSERT INTO projects (
  pro_id, slug, project_name, project_description, total_cost, bhk_type, year_completed,
  timeline_months, project_duration_label, location, work_type, area_of_work, materials_json,
  media_json, video_url, design_style, team_size, warranty_years,
  testimonial_client_name, testimonial_text, testimonial_rating
)
VALUES
(
  4,
  'neev-interiors-golf-course-road-3bhk',
  'Golf Course Road 3BHK Full Home',
  'A balanced full-home transformation with layered lighting, storage planning, and warm material tones.',
  2850000,
  '3BHK',
  2025,
  6,
  '6 months',
  'Golf Course Road, Gurgaon',
  'Full Home',
  'Apartments',
  JSON_ARRAY('BWP Plywood', 'Acrylic Finish', 'Quartz', 'Hafele Hardware'),
  JSON_ARRAY(
    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1615529182904-14819c35db37?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1500&q=80',
    'https://images.pexels.com/photos/6585750/pexels-photo-6585750.jpeg?auto=compress&cs=tinysrgb&w=1500'
  ),
  NULL,
  'Modern',
  12,
  8,
  'Ankit Verma',
  'The layout feels much larger and the finish quality is excellent.',
  5
),
(
  5,
  'tribuz-interiors-dlf-phase-5-luxe-4bhk',
  'DLF Phase 5 Luxe 4BHK',
  'Luxury apartment design with custom wardrobes, calm neutral tones, and a highly coordinated execution plan.',
  3650000,
  '4BHK',
  2025,
  7,
  '7 months',
  'DLF Phase 5, Gurgaon',
  'Full Home',
  'Apartments',
  JSON_ARRAY('Marine Plywood', 'PU Finish', 'Quartzite', 'Hafele Fittings'),
  JSON_ARRAY(
    'https://images.unsplash.com/photo-1493666438817-866a91353ca9?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1615874959474-d609969a20ed?auto=format&fit=crop&w=1500&q=80',
    'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1500'
  ),
  'https://www.youtube.com/embed/dQw4w9WgXcQ',
  'Luxury Contemporary',
  15,
  10,
  'Rohit Sethi',
  'Their planning and follow-through were excellent from concept to handover.',
  5
),
(
  6,
  'silqe-design-studio-sohna-road-villa',
  'Sohna Road Villa Renovation',
  'A villa refresh with improved circulation, premium surfaces, and cleaner architectural detailing.',
  6100000,
  'Villa',
  2025,
  9,
  '9 months',
  'Sohna Road, Gurgaon',
  'Renovation',
  'Villa',
  JSON_ARRAY('Natural Veneer', 'Quartzite', 'Microtopping', 'Solid Surface'),
  JSON_ARRAY(
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
    'https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?auto=format&fit=crop&w=1500&q=80',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
    'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1500'
  ),
  NULL,
  'Modern Luxe',
  18,
  12,
  'Nisha Mehta',
  'The villa feels refined and much more functional than before.',
  5
),
(
  7,
  'classygaze-sector48-workplace-residence',
  'Sector 48 Workspace + Residence',
  'Dual-use interior planning for a compact home office and residence with cleaner zoning.',
  1450000,
  'Commercial',
  2024,
  4,
  '4 months',
  'Sector 48, Gurgaon',
  'Commercial',
  'Commercial',
  JSON_ARRAY('BWP Plywood', 'PU Paint', 'Quartz', 'Glass Partition'),
  JSON_ARRAY(
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
    'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1500&q=80',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s',
    'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1500&q=80'
  ),
  NULL,
  'Modern Functional',
  8,
  5,
  'Aditya Khanna',
  'Very practical space planning and a clean finishing standard.',
  4
),
(
  8,
  'ss-interior-solution-sector56-kitchen-wardrobe',
  'Sector 56 Kitchen + Wardrobe Upgrade',
  'Targeted kitchen and wardrobe work with durable materials and quick execution.',
  980000,
  '3BHK',
  2024,
  3,
  '12 weeks',
  'Sector 56, Gurgaon',
  'Kitchen',
  'Apartments',
  JSON_ARRAY('Marine Plywood', 'PU Paint', 'Hettich Channels'),
  JSON_ARRAY(
    'https://images.unsplash.com/photo-1556912167-f556f1f39fdf?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1600489000022-c2086d79f9d4?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1500&q=80'
  ),
  NULL,
  'Contemporary',
  9,
  5,
  'Manish Jain',
  'Great storage planning and very neat finish work.',
  5
),
(
  9,
  'pahal-design-studio-sector67-2bhk',
  'Sector 67 Space-Smart 2BHK',
  'Compact home optimized with integrated wardrobe design, study units, and cleaner circulation.',
  1250000,
  '2BHK',
  2024,
  4,
  '4 months',
  'Sector 67, Gurgaon',
  'Wardrobe',
  'Apartments',
  JSON_ARRAY('Laminate', 'Marine Plywood', 'Soft Close Hardware'),
  JSON_ARRAY(
    'https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1500&q=80',
    'https://images.pexels.com/photos/3184325/pexels-photo-3184325.jpeg?auto=compress&cs=tinysrgb&w=1500',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q82WISxpWPp5dHBTWHypFOZbRTvc0ST0xQ&s'
  ),
  NULL,
  'Minimal',
  6,
  3,
  'Sakshi Jain',
  'The compact apartment feels much better organized now.',
  4
),
(
  10,
  'archone-dlf-phase-2-villa-luxury',
  'DLF Phase 2 Luxury Villa',
  'Architecture-led villa work with premium detailing, strong material continuity, and a tailored layout.',
  7200000,
  'Villa',
  2025,
  10,
  '10 months',
  'DLF Phase 2, Gurgaon',
  'Renovation',
  'Villa',
  JSON_ARRAY('Veneer', 'Quartz', 'Hafele', 'PU Finish'),
  JSON_ARRAY(
    'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1615874959474-d609969a20ed?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1600210492486-724fe5c67fb2?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=1500&q=80'
  ),
  'https://www.youtube.com/embed/ScMzIvxBSi4',
  'Luxury',
  20,
  12,
  'Kunal Arora',
  'Strong architecture planning and premium finish control throughout.',
  5
),
(
  11,
  'melange-dlf-city-phase-1-premium-4bhk',
  'DLF City Phase 1 Premium 4BHK',
  'A bespoke home with expressive materials, balanced lighting, and elegant custom furniture.',
  5400000,
  '4BHK',
  2025,
  8,
  '8 months',
  'DLF City Phase 1, Gurgaon',
  'Full Home',
  'Apartments',
  JSON_ARRAY('Bespoke Veneer', 'Natural Stone', 'Hafele', 'Luxury Fabrics'),
  JSON_ARRAY(
    'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1500&q=80',
    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1500&q=80',
    'https://images.pexels.com/photos/8867439/pexels-photo-8867439.jpeg?auto=compress&cs=tinysrgb&w=1500'
  ),
  NULL,
  'Modern Luxury',
  16,
  10,
  'Megha Nair',
  'They delivered a beautiful home and kept us informed at each stage.',
  5
);

DELETE FROM pros
WHERE slug IN ('ananya-sharma-interiors', 'raghav-menon-architects', 'vikas-bedi-contracting');
